---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  template:
    metadata:
      name: nginx-rs
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx-rs
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: nginx-rs
