apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort # NodePort 타입 서비스
  selector:
    app: nginx-dp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 # node의 포트로 접속 가능
